// =============================================================================
// MECHS OF NIGHT CITY - DRONE CONTACT HULLS (generated by tools/drones/scan.py)
//
// Each drone's contact points, scanned from its real meshes: the support points along
// 26 directions, in metres from the entity origin (X right, Y forward, Z up), and the
// sight-view sensor mount default (at the nose, centre-of-mass height). Don't edit by
// hand: re-run the scan.
// =============================================================================
module ControllableMechs.Control

public abstract class CMDroneHull {
  public static func Points(kind: String) -> array<Vector4> {
    switch kind {
      case "bombus":
        return [new Vector4(0.019, 0.133, -0.005, 0.0), new Vector4(-0.046, -0.258, 0.128, 0.0), new Vector4(0.237, -0.074, 0.099, 0.0), new Vector4(-0.251, -0.033, 0.094, 0.0), new Vector4(0.000, -0.002, 0.271, 0.0), new Vector4(0.064, 0.163, 0.174, 0.0), new Vector4(0.215, 0.064, 0.108, 0.0), new Vector4(-0.033, 0.224, 0.139, 0.0), new Vector4(-0.215, 0.064, 0.108, 0.0), new Vector4(0.046, -0.258, 0.128, 0.0), new Vector4(0.049, 0.214, 0.028, 0.0), new Vector4(0.000, -0.267, 0.110, 0.0)];
      case "griffin":
        return [new Vector4(-0.036, 0.180, -0.474, 0.0), new Vector4(0.046, -0.531, 0.521, 0.0), new Vector4(0.490, 0.657, 0.115, 0.0), new Vector4(-0.490, 0.657, 0.115, 0.0), new Vector4(0.611, -0.195, -0.045, 0.0), new Vector4(-0.613, -0.194, -0.048, 0.0), new Vector4(0.094, -0.700, -0.120, 0.0), new Vector4(0.482, 0.424, -0.397, 0.0), new Vector4(-0.482, 0.423, -0.397, 0.0), new Vector4(0.072, 0.471, 0.318, 0.0), new Vector4(-0.446, -0.484, 0.045, 0.0), new Vector4(0.446, -0.484, 0.045, 0.0)];
      case "wyvern":
        return [new Vector4(0.010, 0.311, -0.007, 0.0), new Vector4(-0.068, -0.469, 0.386, 0.0), new Vector4(0.015, 0.051, 0.461, 0.0), new Vector4(-0.150, -0.184, 0.051, 0.0), new Vector4(-0.068, 0.470, 0.386, 0.0), new Vector4(0.074, -0.459, 0.058, 0.0), new Vector4(0.150, -0.180, 0.150, 0.0), new Vector4(0.001, 0.486, 0.181, 0.0), new Vector4(0.150, 0.185, 0.051, 0.0), new Vector4(-0.150, 0.030, 0.400, 0.0), new Vector4(0.150, -0.027, 0.400, 0.0), new Vector4(-0.094, 0.395, 0.058, 0.0)];
      case "octant":
        return [new Vector4(-0.129, 1.419, -0.760, 0.0), new Vector4(0.362, -1.666, 0.317, 0.0), new Vector4(-1.330, 0.047, 0.671, 0.0), new Vector4(1.336, 0.525, 0.603, 0.0), new Vector4(-0.319, -0.721, 1.066, 0.0), new Vector4(-0.790, -0.757, -0.237, 0.0), new Vector4(0.802, 0.798, -0.380, 0.0), new Vector4(0.790, -0.757, -0.237, 0.0), new Vector4(-0.983, 1.056, -0.294, 0.0), new Vector4(1.226, -0.527, 0.663, 0.0), new Vector4(0.048, 1.668, 0.095, 0.0), new Vector4(0.013, -1.360, -0.365, 0.0)];
    }
    let none: array<Vector4>;
    return none;
  }

  // sensor mount defaults (cm): height above the origin, forward of it
  public static func SensorUpCm(kind: String) -> Int32 {
    switch kind {
      case "bombus": return 13;
      case "griffin": return 0;
      case "wyvern": return 22;
      case "octant": return 15;
    }
    return 10;
  }

  public static func SensorFwdCm(kind: String) -> Int32 {
    switch kind {
      case "bombus": return 29;
      case "griffin": return 74;
      case "wyvern": return 54;
      case "octant": return 174;
    }
    return 35;
  }
}
